"""Add Incidente, LogPaciente, update Guardia

Revision ID: 022897e49b04
Revises: f9bf5eaf90df
Create Date: 2026-02-25 22:15:20.618030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022897e49b04'
down_revision = 'f9bf5eaf90df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('severidad', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidadores.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('condicion', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidadores.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_inicio', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('hora_fin', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ubicacion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=True))
        batch_op.alter_column('horas_trabajadas',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.alter_column('horas_trabajadas',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('estado')
        batch_op.drop_column('ubicacion')
        batch_op.drop_column('hora_fin')
        batch_op.drop_column('hora_inicio')

    op.drop_table('logs_pacientes')
    op.drop_table('incidentes')
    # ### end Alembic commands ###
