"""add estado_informe and calificacion to guardia

Revision ID: 468edbf42cf5
Revises: 022897e49b04
Create Date: 2026-02-25 22:51:43.010987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468edbf42cf5'
down_revision = '022897e49b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_informe', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('calificacion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comentario_calificacion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.drop_column('comentario_calificacion')
        batch_op.drop_column('calificacion')
        batch_op.drop_column('estado_informe')

    # ### end Alembic commands ###
