"""reset schema con cuidador_preferido_id

Revision ID: ba79c12473b0
Revises: 468edbf42cf5
Create Date: 2026-03-03 12:20:37.020619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba79c12473b0'
down_revision = '468edbf42cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuidadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('cuidador_preferido_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuidador_preferido_id'], ['cuidadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('contacto_familia', sa.String(length=100), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('metodo', sa.String(length=50), nullable=True),
    sa.Column('confirmado', sa.Boolean(), nullable=True),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.String(length=10), nullable=True),
    sa.Column('hora_fin', sa.String(length=10), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('horas_trabajadas', sa.Float(), nullable=True),
    sa.Column('informe', sa.Text(), nullable=True),
    sa.Column('estado_informe', sa.String(length=50), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('comentario_calificacion', sa.Text(), nullable=True),
    sa.Column('cuidador_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidadores.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('severidad', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidadores.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('condicion', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidadores.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs_pacientes')
    op.drop_table('incidentes')
    op.drop_table('guardias')
    op.drop_table('pagos')
    op.drop_table('pacientes')
    op.drop_table('documentos')
    op.drop_table('usuarios')
    op.drop_table('cuidadores')
    # ### end Alembic commands ###
